# **Class_12**

![](images.jpg)

### **introduction**

- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra,
  fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.
- linear algebra library - typically 'Intel MKL' or 'OpenBLAS' already exist in numpy 
  (jin ki base py 
   numpy library bni hai )


### **Why Use NumPy?**
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
  NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
  The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
  Arrays are very frequently used in data science, where speed and resources are very important.


### **How to install NumPy in vsCode?**
To install Numpy run this command "pip install numpy" 

in terminal window of VsCode.

> Not in OutPut window.

*NumPy is already installed Jupyter Notebook.*

### **How to use?**
To access Numpy and its functions import it in your python code lik this:


In [16]:
import numpy as np # np is abbreviate of numpy

### **How it looks like?**


In [17]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

- ### **Lists**

In [18]:
Akif = [1,4,6,8,12] #Akif is a list name 
Akif
type(list) #chech data type

type

![](np_l.jpg)

### **What is an array?**
- An array is central data structure of the NumPy library.
- An array is a grid of values and it contains information about the raw data,how to locate an element and how to       interpret an element.
- It has a grid of elements that can be indexed in various ways.
- The elements are all of the same type, referred to as the array dtype.
- An array can be indexed by a tuple of non-negative integers, by booleans, by another array or by integers.


### **What is the rank of an array?**
- The rank of the array is the number of dimensions 

### **What is the shape of an array?**
- The shape of the array is a tuple of integers giving the size of the array along each dimension


In [19]:
import numpy as np

In [20]:
# An array example 
a = np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [21]:
type(a)

numpy.ndarray

numpy.ndarray means numerical of python.number of dimension array k is mein koi dimension hai 1D hai ya 2D 



In [22]:
# Example of 2D array
# list of lists
k= np.array([[5,5,5,5],[5,5,5,5],[5,5,5,5]])
k

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### **Vector**

A vector is an array with a single dimension(There is no difference between row and column vector)

![](download.png)

### **Matrix**

A matrix refer to an array with two dimensions.

![](matrix.png)


Best Example of Vector and Matrix is School Assembly

- # **1-D Array** :

In [23]:
import numpy as np

In [24]:
a =np.array([8,9,10,12])
a

array([ 8,  9, 10, 12])

In [25]:
type(a)

numpy.ndarray

In [26]:
len(a)

4

In [27]:
# Indexing check
a[2]

10

> Note: The numpy ndarray class is used to represent noth matrixes and vectors 

In [28]:
# list of Lists 
k = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
k

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [29]:
type(k)

numpy.ndarray

In [20]:
len(k)

4

In [26]:
k[0:2]

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [27]:
k[0:] #  you can also print as whole array by this one

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

### **Attributes of an array?**

- An array is a fixed-size container of items of the same type and size.
- The number of dimensions and items in an array is defined by its shape.
- The shape of the array is a tuple of integers giving the size of the array along each dimension.
- In NumPy, dimensions are called axes.

Axis

 ![](axis.png)

In [28]:
import numpy as np

In [32]:
i= np.array([[1,2,1,2],[3,3,3,3],[4,4,4,4],[5,5,5,5],[6,6,6,6]])
i


array([[1, 2, 1, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In above example array has 2 axis. The first axis has a length of 4 and the second axis has a length of 5.

2-Axis = length of first axis is 4 and the second axis length of 5


### **How to create an array?**

# 1-D


In [92]:
import numpy as np 

In [93]:
a = np.array([1,1,1,1])
a

array([1, 1, 1, 1])

we can also create an array it as 

In [94]:
np.array([2,2,2,2,2])

array([2, 2, 2, 2, 2])

#### We can also create an array in other ways rather than creating from a sequence of elements.

In [95]:
# With zero () Function
a = np.zeros(3)
a

array([0., 0., 0.])

In [41]:
k = np.ones(15)
k


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
# Create an empty array with 3 elements 
i = np.empty(3)
i

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [44]:
# With range of elements
s = np.arange(7)
s 

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
# with specific range of elements 
a = np.arange(2 , 22)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [47]:
# with continue...
f = np.arange(1,22 ,3)
f

array([ 1,  4,  7, 10, 13, 16, 19])

In [56]:
# linely spaced arrays : Mtlb ye k hm aik specific range provide krain gy k kaha se kaha tk array print
# krni hai or ye bhi btain gy k us range k drmiyan kitni values ayen gi.
m = np.linspace(0,30,num=6) 
m

array([ 0.,  6., 12., 18., 24., 30.])

In [57]:
# specific datatype in array
k = np.ones(5,dtype=np.int8)
k

array([1, 1, 1, 1, 1], dtype=int8)

In [62]:
s = np.arange(5,dtype=np.float64)
s

array([0., 1., 2., 3., 4.])

### **How to create an array?**

# 2-D


In [96]:
import numpy as np
n =np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
type(n)

numpy.ndarray

In [98]:
len(n)

3

In [99]:
n[2] # Indexing 

array([7, 8, 9])

In [100]:
# 2-D with zero() function 
n = np.zeros((4,5))
n


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
# 2-D with ones() Function
n= np.ones((7,3))
n

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
# 2-D with empty() Function
n= np.empty((3,6))
n

array([[1.70256031e-312, 5.23709585e-322, 0.00000000e+000,
        0.00000000e+000, 9.34603678e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        4.24819624e+180, 3.02579561e-110, 6.09343068e-013],
       [3.36191100e-110, 4.90900643e+252, 1.94918511e-153,
        6.32672800e+180, 4.74483502e+170, 2.38435632e-038]])

### **How to create an array?**

# 3-D


![](3d.png)

In [104]:
import numpy as np

In [111]:
# Making and reshaping a 3-D array
b = np.arange(30).reshape(2, 3, 5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])