# **Class_13**

## _**Numpy Practice Session**_

In [2]:
import numpy as np

> ### **Create an array using numpy**

## **1-D** Array

In [3]:
# press np. and you can use for different purpose your own choice 
# here we will use array 
fast_food = np.array(["Pakora", "Samosa,", "Raita"])
fast_food


array(['Pakora', 'Samosa,', 'Raita'], dtype='<U7')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(fast_food)

numpy.ndarray

In [7]:
len(fast_food)

3

In [8]:
len(price)

3

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
#  if you want to print only Samosa then folow this code
# you will put only index number of Samosa 
fast_food[1]

'Samosa,'

In [11]:
# fast_food and price both are object of array 
price.mean()

5.0

**Note:-**

- Method of make an array

1 self create array\
2 arange array

In [13]:
# zeros method 
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [38]:
# To make array of one 
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

#### **With empty() Fucntion**
The function empty creates an array whose initial content is random and depends on the state of the memory.

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards.

In [39]:
# an empty array 
a = np.empty(3)
a


array([4.74534327e-312, 0.00000000e+000, 4.94065646e-324])

In [40]:
# arange method array 
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# Specify arange array
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
# specify interval arange array
np.arange(0,32,3) # here is 3 interval number  

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

> ### **Table**

In [13]:
#  table of ten
np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

8- Line spaced Array
Mtlb ye k hm aik specific range provide krain gy k kaha se kaha tk array print

krni hai or ye bhi btain gy k us range k drmiyan kitni values ayen gi.

In [44]:
# Specific line space 
#  that mean 0-2.5 = 2.5 and also will be answer when 2.5-5=2.5
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [96]:
#  Specify your data type 
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [46]:
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### **Array Function**

In [47]:
# Sort Array
# Descending Order
a=np.array([2,75,5,7,1,20,45,60,90,100])
a

array([  2,  75,   5,   7,   1,  20,  45,  60,  90, 100])

In [48]:
# Ascending Order
a.sort()
a


array([  1,   2,   5,   7,  20,  45,  60,  75,  90, 100])

In [49]:
b= np.array([2,4,21,67,45,87,6,70,90])
b

array([ 2,  4, 21, 67, 45, 87,  6, 70, 90])

In [50]:
b.sort()
b

array([ 2,  4,  6, 21, 45, 67, 70, 87, 90])

In [51]:
# Concatenate 
c = np.concatenate ((a,b))
c

array([  1,   2,   5,   7,  20,  45,  60,  75,  90, 100,   2,   4,   6,
        21,  45,  67,  70,  87,  90])

In [52]:
c.sort()
c

array([  1,   2,   2,   4,   5,   6,   7,  20,  21,  45,  45,  60,  67,
        70,  75,  87,  90,  90, 100])

## **2-D** Array

In [53]:
a = np.array([[2,5,8,1,], [10,6,11,15]])
a

array([[ 2,  5,  8,  1],
       [10,  6, 11, 15]])

In [54]:
b = np.array([[12,34,10,45], [34,65,78,90]])
b

array([[12, 34, 10, 45],
       [34, 65, 78, 90]])

In [55]:
# Concatenate 
#  agr hm axis=1 stack kr dein tu y-axis waly x-axis py aa jayn gy
c= np.concatenate((a,b), axis=0)
c 

array([[ 2,  5,  8,  1],
       [10,  6, 11, 15],
       [12, 34, 10, 45],
       [34, 65, 78, 90]])

In [56]:
c= np.concatenate((a,b), axis=1)
c 

array([[ 2,  5,  8,  1, 12, 34, 10, 45],
       [10,  6, 11, 15, 34, 65, 78, 90]])

#### **Shape and Size of an Array**

![](ndnp.png)

In [97]:
ex = np.array([[[2,5,8,1,],
                            [10,6,11,15]],

                           [[12,34,10,45],
                            [34,65,78,90]],
                           [[12,34,10,45], 
                            [34,65,78,90]]])
ex

array([[[ 2,  5,  8,  1],
        [10,  6, 11, 15]],

       [[12, 34, 10, 45],
        [34, 65, 78, 90]],

       [[12, 34, 10, 45],
        [34, 65, 78, 90]]])

In [58]:
ex.shape
#  here is 3 number of dimensions 2 number of rows and 4 number of columns

(3, 2, 4)

In [59]:
#  To find the number of  Dimensions 
ex.ndim

3

In [60]:
s = np.array([[12,34,21],
              [92,73,14],
              [12,76,89]])
s 

array([[12, 34, 21],
       [92, 73, 14],
       [12, 76, 89]])

In [61]:
s.ndim

2

In [62]:
# size mean number of elements 
s.size

9

In [63]:
a.shape

(2, 4)

### **Reshape Function**

#### Reshape an Array

You can use reshape() to reshape your array.

*gg.reshape(4,3)*

In above line 4 is number of columns and 3 is number of rows.

In [64]:
import numpy as np

gg = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

gg.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
gg.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
k = np.arange(16) # 4*4
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
#  reshape
s= k.reshape(4,4) # 4*4=16
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
# reshape 
np.reshape(k,newshape=(1,16), order='C')    

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

### Convert 1-D array into 2-D 

In [69]:
a = np.array([1,2,3,4,5,6,7,8,9])
a 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.shape

(9,)

#### **This is two dimension array as you can see blew invisible  and Row wise conversion** 


In [71]:
b = a [ np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### **column wise**

In [72]:
c = a [  : ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### **indexing array**

In [73]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a [2:9]  

array([3, 4, 5, 6, 7, 8, 9])

> ### **Mathematical Operator_with_Array**

In [75]:
a*3 # Multiplication

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [76]:
a+4  # Addition

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [77]:
a / 2 #     Division

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### => Sum of Elements in Array

In [80]:
# Sum of an array
a.sum()

45

In [84]:
a.max()

9

In [83]:
a.min()

1

### **Indexing and slicing**

![](index_slic.png)

In [7]:
q=np.arange(2,20,2)
q

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
q[6]

14

In [9]:
# 3: ka mtlb hai k 3rd index se agy jtny bhi hain print kr do..
q[3:]

array([ 8, 10, 12, 14, 16, 18])

In [10]:
q[4:8]

array([10, 12, 14, 16])

In [11]:
q[-4]

12

In [12]:
q[-4:]

array([12, 14, 16, 18])

### **What is ndarray?**
“ndarray,” is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions.

##### **Some other Operations**

- You can easily print all of the values in the array that are less than 14.


In [13]:

(q[q<14])


array([ 2,  4,  6,  8, 10, 12])

- You can also select, for example, numbers that are equal to or

- greater than 8, and use that condition to index an array.

In [14]:
q1=(q[q>=8])
q1

array([ 8, 10, 12, 14, 16, 18])

In [15]:
q1[0]

8

- You can select elements that are divisible by 3:

In [16]:
(q[q%3==0])


array([ 6, 12, 18])

- you can select elements that satisfy two conditions using the & and | operators:


In [17]:
q[(q > 2) & (q < 16)]

array([ 4,  6,  8, 10, 12, 14])

In [18]:
(q > 5) | (q == 15)


array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [21]:
aa = np.arange(0,100,10)
aa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### **Vstack & Hstack**
You can also stack two existing arrays, both vertically and horizontally.

Let’s say you have two arrays, b1 and b2:

In [22]:
b1 = np.array([[1,2,3,4], [5,6,7,8]])
b1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
b2 = np.array([[4,3,2,1],[8,7,6,5]])
b2

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

**=> Vstack**

vertically with vstack:

In [24]:
np.vstack((b1,b2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1],
       [8, 7, 6, 5]])

**=> Hstack**

horizontally with hstack:

In [25]:
np.hstack((b1,b2))


array([[1, 2, 3, 4, 4, 3, 2, 1],
       [5, 6, 7, 8, 8, 7, 6, 5]])

> ### **Statistical functions**

### **1-Mean**

### **Mean of 1-D Arrya**

In [78]:
arr = np.array([10, 25, 36, 47, 51])
np.mean(arr)

33.8

### **Mean of 2-D Arrya**

In [81]:
a = np.array([[11, 22, 30], [40, 55, 54], [74, 80, 94]])
np.mean(a)

51.111111111111114

In [82]:
np.mean(a, axis=0) #along axis 0


array([41.66666667, 52.33333333, 59.33333333])

In [83]:
np.mean(a, axis=1) # along axis 1


array([21.        , 49.66666667, 82.66666667])

### **Mean of a boolean array**

In [85]:
arr = np.array([True, False, True, True, False])
arr

array([ True, False,  True,  True, False])

In [86]:
np.mean(arr)


0.6

### **2-Meadian**

### **Median of 1-D Array**

In [87]:
arr = np.array([34, 14, 47, 27, 52])
median = np.median(arr)
print(median)

34.0


### **Median of 2-D Array**

In [92]:
arr1 = np.array([[12, 32, 33], [43, 35, 36], [37, 82, 91],[66,77,82]])
arr1

array([[12, 32, 33],
       [43, 35, 36],
       [37, 82, 91],
       [66, 77, 82]])

In [93]:
median = np.median(arr1)
print(median)

40.0


In [89]:
median= np.median(arr, axis=0) # along axis 0
median

array([40., 56., 59.])

In [90]:
np.median(arr, axis=1) #along axis 1


array([32., 36., 82., 77.])

### **Variance**

variance = sum((x - mean) ** 2) / N

In [94]:
import numpy as np

In [95]:
arr = np.array([15, 25, 35, 45, 75])
np.var(arr)

424.0