# **Class_13**

## _**Numpy Practice Session**_

In [1]:
import numpy as np

> ### **Create an array using numpy**

## **1-D** Array

In [2]:
# press np. and you can use for different purpose your own choice 
# here we will use array 
fast_food = np.array(["Pakora", "Samosa,", "Raita"])
fast_food


array(['Pakora', 'Samosa,', 'Raita'], dtype='<U7')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(fast_food)

numpy.ndarray

In [9]:
len(fast_food)

3

In [10]:
len(price)

3

In [16]:
price[0:]

array([5, 5, 5])

In [17]:
#  if you want to print only Samosa then folow this code
# you will put only index number of Samosa 
fast_food[1]

'Samosa,'

In [19]:
# fast_food and price both are object of array 
price.mean()

5.0

**Note:-**
- Method of make an array\
1 self create array\
2 arange array

In [20]:
# zeros method 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
# To make array of one 
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

#### **With empty() Fucntion**
The function empty creates an array whose initial content is random and depends on the state of the memory.

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards.

In [32]:
# an empty array 
a = np.empty(3)
a


array([2.05117489e-312, 0.00000000e+000, 6.47591605e-319])

In [34]:
# arange method array 
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# Specify arange array
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
# specify interval arange array
np.arange(0,32,3) # here is 3 interval number  

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [2]:
#  table of five 
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

8- Line spaced Array
Mtlb ye k hm aik specific range provide krain gy k kaha se kaha tk array print

krni hai or ye bhi btain gy k us range k drmiyan kitni values ayen gi.

In [9]:
# Specific line space 
#  that mean 0-2.5 = 2.5 and also will be answer when 2.5-5=2.5
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
#  Specify your data type 
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [11]:
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### **Array Function**

In [13]:
# Sort Array
# Descending Order
a=np.array([2,75,5,7,1,20,45,60,90,100])
a

array([  2,  75,   5,   7,   1,  20,  45,  60,  90, 100])

In [14]:
# Ascending Order
a.sort()
a


array([  1,   2,   5,   7,  20,  45,  60,  75,  90, 100])

In [15]:
b= np.array([2,4,21,67,45,87,6,70,90])
b

array([ 2,  4, 21, 67, 45, 87,  6, 70, 90])

In [16]:
b.sort()
b

array([ 2,  4,  6, 21, 45, 67, 70, 87, 90])

In [17]:
# Concatenate 
c = np.concatenate ((a,b))
c

array([  1,   2,   5,   7,  20,  45,  60,  75,  90, 100,   2,   4,   6,
        21,  45,  67,  70,  87,  90])

In [18]:
c.sort()
c

array([  1,   2,   2,   4,   5,   6,   7,  20,  21,  45,  45,  60,  67,
        70,  75,  87,  90,  90, 100])

## **2-D** Array

In [24]:
a = np.array([[2,5,8,1,], [10,6,11,15]])
a

array([[ 2,  5,  8,  1],
       [10,  6, 11, 15]])

In [25]:
b = np.array([[12,34,10,45], [34,65,78,90]])
b

array([[12, 34, 10, 45],
       [34, 65, 78, 90]])

In [30]:
# Concatenate 
#  agr hm axis=1 stack kr dein tu y-axis waly x-axis py aa jayn gy
c= np.concatenate((a,b), axis=0)
c 

array([[ 2,  5,  8,  1],
       [10,  6, 11, 15],
       [12, 34, 10, 45],
       [34, 65, 78, 90]])

In [32]:
c= np.concatenate((a,b), axis=1)
c 

array([[ 2,  5,  8,  1, 12, 34, 10, 45],
       [10,  6, 11, 15, 34, 65, 78, 90]])

In [37]:
ex = np.array([[[2,5,8,1,],
                            [10,6,11,15]],

                           [[12,34,10,45],
                            [34,65,78,90]],
                           [[12,34,10,45], 
                            [34,65,78,90]]])
ex

array([[[ 2,  5,  8,  1],
        [10,  6, 11, 15]],

       [[12, 34, 10, 45],
        [34, 65, 78, 90]],

       [[12, 34, 10, 45],
        [34, 65, 78, 90]]])

In [49]:
ex.shape
#  here is 3 number of dimensions 2 number of rows and 4 number of columns

(3, 2, 4)

In [39]:
#  To find the number of  Dimensions 
ex.ndim

3

In [43]:
s = np.array([[12,34,21],
              [92,73,14],
              [12,76,89]])
s 

array([[12, 34, 21],
       [92, 73, 14],
       [12, 76, 89]])

In [44]:
s.ndim

2

In [46]:
# size mean number of elements 
s.size

9

In [48]:
a.shape

(2, 4)

### **Reshape Function**

In [61]:
k = np.arange(16) # 4*4
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
#  reshape
s= k.reshape(4,4) # 4*4=16
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
# reshape 
np.reshape(k,newshape=(1,16), order='C')    

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

### Convert 1-D array into 2-D 

In [64]:
a = np.array([1,2,3,4,5,6,7,8,9])
a 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a.shape

(9,)

#### **This is two dimension array as you can see blew invisible  and Row wise conversion** 


In [67]:
b = a [ np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### **column wise**

In [68]:
c = a [  : ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### **indexing array**

In [70]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a [2:9]  

array([3, 4, 5, 6, 7, 8, 9])

> ### **You can also how to  add and multiply an array**

In [76]:
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [78]:
a+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [80]:
# Sun of an array
a.sum()

45

In [81]:
a.mean()    

5.0

### **What is ndarray?**
“ndarray,” is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions.